### PR TITLE
Restore Colab support for example notebooks

### PR DESCRIPTION
**Pull request by flferretti**
This PR restore the support for Google Colab for the example notebooks previously removed in #152. 

----
📚 Documentation preview 📚: https://jaxsim--154.org.readthedocs.build//154/

### CODE REVIEW

**Comment by flferretti** [comment]
I had a small issue on the visualization that has been solved in https://github.com/ami-iit/jaxsim/pull/154/commits/bea65bc1a7ac331ae52a2219fe02e58fe3406a30. Apparently in Colab, `libGL` requires a `DISPLAY` environment variable to be set. For this reason I used `xvfb` to create a dummy one.

Ready for review

**Comment by traversaro** [comment]
> Apparently in Colab, `libGL` requires a `DISPLAY` environment variable to be set. For this reason I used `xvfb` to create a dummy one.

That is strange, as long as you use `egl` that should not be necessary. Not blocking the PR, but what was the error?

**Comment by flferretti** [comment]
> > Apparently in Colab, `libGL` requires a `DISPLAY` environment variable to be set. For this reason I used `xvfb` to create a dummy one.
> 
> That is strange, as long as you use `egl` that should not be necessary. Not blocking the PR, but what was the error?

image

**Comment by traversaro** [comment]
Thanks, I wonder why this is not happening in official mujoco colabs. Anyhow, no problem.

**Review by xela-95 — APPROVED** [review]

**Comment by flferretti** [comment]
> Thanks, I wonder why this is not happening in official mujoco colabs. Anyhow, no problem.

I have no idea to be honest, I have also seen that in Mujoco it works

**Comment by traversaro** [comment]
> > Thanks, I wonder why this is not happening in official mujoco colabs. Anyhow, no problem.
> 
> I have no idea to be honest, I have also seen that in Mujoco it works

Probably the difference is due to the fact that `glfw` is also installed or somehow is selected as backend?

**Pull request merged**
