### PR TITLE
Allow to use the link frame when setting or getting forces using the references helper

### PR DESCRIPTION
**Pull request by diegoferigo**
Before this PR, the helper was expecting the following:

- `JaxSimModelReferences.link_forces` returned ${}_W \mathbf{f}_L$, ${}_B \mathbf{f}_L$, ${}\_{B[W]} \mathbf{f}_L$ in inertial-fixed, body-fixed, and mixed representations, respectively.
- `JaxSimModelReferences.apply_link_forces` expected to receive ${}_W \mathbf{f}_L$, ${}_B \mathbf{f}_L$, ${}\_{B[W]} \mathbf{f}_L$ in inertial-fixed, body-fixed, and mixed representations, respectively.

After this PR, if `use_link_frame=True`, these methods behave as follows:

- `JaxSimModelReferences.link_forces` returns ${}_W \mathbf{f}_L$, ${}_L \mathbf{f}_L$, ${}\_{L[W]} \mathbf{f}_L$ in inertial-fixed, body-fixed, and mixed representations, respectively.
- `JaxSimModelReferences.apply_link_forces` expects to receive ${}_W \mathbf{f}_L$, ${}_L \mathbf{f}_L$, ${}\_{L[W]} \mathbf{f}_L$ in inertial-fixed, body-fixed, and mixed representations, respectively.

----
📚 Documentation preview 📚: https://jaxsim--164.org.readthedocs.build//164/

### CODE REVIEW

**Comment by diegoferigo** [comment]
Note that the default in body-fixed and mixed is using $B$. This is useful since these forces can be automatically projected to the generalized coordinates using [`jaxsim.api.model.generalized_free_floating_jacobian`](https://github.com/ami-iit/jaxsim/blob/f24be35f446fd36d891e1aa6ed4c536518a7923f/src/jaxsim/api/model.py#L404C5-L409) as it is done for example [here](https://github.com/ami-iit/jaxsim/blob/f24be35f446fd36d891e1aa6ed4c536518a7923f/src/jaxsim/api/model.py#L723-L745).

With this PR, I'm not sure if also this behavior should be changed. In other words, should all the `link_forces` in body-fixed and mixed be ${}_L \mathbf{f}$ and ${}\_{L[W]} \mathbf{f}$? What would be more intuitive to users?#164 

cc @traversaro for a quick feedback.

**Review by flferretti — APPROVED** [review]
LGTM, thanks!

**Review by xela-95 — APPROVED** [review]

**Comment by diegoferigo** [comment]
> Interesting, there is any reason why the jacobian is not returning the matrix $J$ such that [...]

I guess that the main reason that triggered the usage of $B$ and $B[W]$ in the output representation of the Jacobian is that our RBDA [compute efficiently the doubly-left full Jacobian](https://github.com/ami-iit/jaxsim/blob/f24be35f446fd36d891e1aa6ed4c536518a7923f/src/jaxsim/api/model.py#L433-L437) ${}^B J\_{W,\\\_/B}$ (refer to #121). Therefore, the body-fixed representation of the jacobians computed with `jaxsim.api.model.generalized_free_floating_jacobian` considers $B$ instead of $L$. Instead, `jaxsim.api.link.jacobian` returns the Jacobian you were expecting, i.e. ${}^L J_{W,L}$ (see test [here](https://github.com/ami-iit/jaxsim/blob/f24be35f446fd36d891e1aa6ed4c536518a7923f/tests/test_api_link.py#L117-L160)).

You can check for the [`test_model_jacobian`](https://github.com/ami-iit/jaxsim/blob/f24be35f446fd36d891e1aa6ed4c536518a7923f/tests/test_api_model.py#L251-L317) for the intended usage. I guess all boils down to something related to this PR: what frame should the references helper use when the representation is set to body-fixed or inertial? If we want to complete ditch using $B$ and $B[W]$ for this (because it may not make a lot of sense), this could be the right moment - and I need to figure out if there are other motivations for this behavior to make sense.

**Comment by traversaro** [comment]
That for the explanation, this is much more clear.

Personally I would find a bit confusing any function that returns or accepts 6D forces written as ${}_W \mathbf{f}_L$, ${}_B \mathbf{f}_L$, ${}\_{B[W]} \mathbf{f}_L$ instead of ${}_W \mathbf{f}_L$, ${}_L \mathbf{f}_L$, ${}\_{L[W]} \mathbf{f}_L$ , especially in mixed mode (why I should write the force applied to the hand with the origin in the base link and the orientation of the world? The nice thing of mixed notation is that you preserve a reasonable point for expressing velocity and forces, if we expressed them as $B[W]$ we kind of lose that. If the methods are meant to be use used by users of jaxsim (and not only internally) my feeling is that the default should use , that is by the way compatible with `jaxsim.api.link.jacobian` and the old iDynTree methods.

**Comment by diegoferigo** [comment]
> If the methods are meant to be use used by users of jaxsim (and not only internally) my feeling is that the default should use , that is by the way compatible with `jaxsim.api.link.jacobian` and the old iDynTree methods.

I totally agree. I'll have a look at this, it shouldn't require a lot of work. I'm not sure at this point if this PR makes sense to be merged, probably I'll include the relevant changes in the new PR with the updated Jacobians.

**Comment by diegoferigo** [comment]
Superseeded by #167. Closing.

**Pull request closed without merging**
