### PR TITLE
Add pre-commit configuration

### PR DESCRIPTION
**Pull request by flferretti**
This PR adds a pre-commit configuration file that includes hooks for checking AST, merge conflicts, YAML syntax, end-of-file, trailing whitespace, and code formatting using Black and isort.

----
📚 Documentation preview 📚: https://jaxsim--86.org.readthedocs.build//86/

### CODE REVIEW

**Comment by diegoferigo** [comment]
Mmh I never liked too much the idea behind committed pre-commits, but in the same time I never investigated in much depth the approach. I want to know more what's your experience with them.

What I dislike is that often I create WIP commits locally (and also push them remotely), and in most cases they are not compliant with the pre-commits rules. I don't want those commits to get blocked or require any additional effort on my side. We do have CI tests before merging PRs for this.

Since these rules get hooked into your personal git configuration, is it an option to just keep them local?

**Comment by traversaro** [comment]
> This PR adds a pre-commit configuration file that includes hooks for checking AST, merge conflicts, YAML syntax, end-of-file, trailing whitespace, and code formatting using Black and isort.
> 
> 📚 Documentation preview 📚: https://jaxsim--86.org.readthedocs.build//86/

@flferretti can you add a line or two either in the README or somewhere where you see fit explaining either how to use this pre-commit files, or a link to related documentation? I guess most members of AMI (that could contribute to the library) are not aware of how this work.

**Comment by flferretti** [comment]
> @flferretti can you add a line or two either in the README or somewhere where you see fit explaining either how to use this pre-commit files, or a link to related documentation? I guess most members of AMI (that could contribute to the library) are not aware of how this work.

Sure @traversaro! What about adding a `CONTRIBUTING` file?

**Comment by traversaro** [comment]
> > @flferretti can you add a line or two either in the README or somewhere where you see fit explaining either how to use this pre-commit files, or a link to related documentation? I guess most members of AMI (that could contribute to the library) are not aware of how this work.
> 
> Sure @traversaro! What about adding a [`CONTRIBUTING`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file?

Sure, as you prefer.

**Comment by flferretti** [comment]
@traversaro I opened https://github.com/ami-iit/jaxsim/pull/87 to add a `CONTRIBUTING` file to the repo. I put the instructions for using the pre-commit in a separate commit, so we can eventually drop it if this doesn't get merged.

**Review by diegoferigo — APPROVED** [review]

**Comment by diegoferigo** [comment]
I found interesting information for beginners in the following blog post:

https://www.elliotjordan.com/posts/pre-commit-01-intro/

**Pull request merged**
