### PR TITLE
Add `readthedocs` based documentation for the JAXsim API

### PR DESCRIPTION
**Pull request by flferretti**
This PR will introduce the baseline for a [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com) documentation for JAXsim.

### CODE REVIEW

**Comment by flferretti** [comment]
The documentation is now available at https://jaxsim.readthedocs.io/

C.C. @CarlottaSartore @S-Dafarra @YuchuanLu

**Comment by diegoferigo** [comment]
Mmh I don't remember closing this, probably it happened by mistake from my phone :) reopening

**Comment by flferretti** [comment]
I'll reopen this as I cannot change the base branch after closing

**Comment by flferretti** [comment]
I'll reopen this as I cannot change the base branch after closing

**Pull request closed without merging**
