### PR TITLE
Add example notebook for rigid body dynamics 

### LINKED ISSUE #194: Add more advanced example notebooks
As the library starts to have more users, the need for a more complete documentation and examples naturally emerges, as seen in #175 and #187. For this reason, this issue aims at showing more than the basics JaxSim features already presented in the [existing notebooks](https://github.com/amii-iit/jaxsim/blob/main/examples). 

The idea is both to improve the existing examples by simplifying the visualisation logic when using headless rendering and to add one or more notebooks with more advanced use-cases using e.g. reinforcement learning or model-based control architectures.

### PR DESCRIPTION
**Pull request by flferretti**
This PR adds an example notebook for showing the use of JaxSim as a multibody dynamics library. Moreover, some refinements to the existing examples have been made.

Closes #194 

----
📚 Documentation preview 📚: https://jaxsim--261.org.readthedocs.build//261/

### CODE REVIEW

**Comment by diegoferigo** [comment]
@flferretti I'm done with my updates to the notebook. Feel free to either review the changes or directly update it, if needed. In order to run successfully, it needs an unmerged change from the ongoing contact refactoring.

**Comment by flferretti** [comment]
Thanks a lot Diego! I have amended the last commit to remove the cell outputs, for the rest it looks great

**Comment by diegoferigo** [comment]
I am experience a broken rendering of video on the notebooks. Regardless, let me merge #265 first, then I'll rebase this PR on top of that one.

**Comment by flferretti** [comment]
> I am experience a broken rendering of video on the notebooks. Regardless, let me merge #265 first, then I'll rebase this PR on top of that one.

If you look at the built docs in the PR description, the videos work fine. Do you have that problem only locally?

**Comment by diegoferigo** [comment]
> > I am experience a broken rendering of video on the notebooks. Regardless, let me merge #265 first, then I'll rebase this PR on top of that one.
> 
> If you look at the built docs in the PR description, the videos work fine. Do you have that problem only locally?

It was here, https://github.com/ami-iit/jaxsim/pull/265#issuecomment-2419181263. My bad, I moved an import without also moving the export of `MUJOCO_GL`.

**Pull request merged**
